language: java
jdk:
  - oraclejdk11

script:
  - ./mvnw install -DskipTests=true -B
  - ./mvnw test -B
  - ./mvnw package -DskipTests=true -B

after_success:
  - bash <(curl -s https://codecov.io/bash)